apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rag-chat
resources:
  - namespace.yaml
  - configmap.yaml
  - api.yaml
  - observability.yaml
configMapGenerator:
  - name: grafana-dashboard
    files:
      - api-overview.json=api-overview.json
    options:
      disableNameSuffixHash: true