apiVersion: v1
kind: Secret
metadata:
  name: rag-secrets
  namespace: rag-chat
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://<username>:<password>@<cluster-host>/chatbot?retryWrites=true&w=majority"
  OLLAMA_API_KEY: "<your-ollama-api-key>"
  TAVILY_API_KEY: "<your-tavily-api-key>"
  GRAFANA_SMTP_USER: "<smtp-user>"
  GRAFANA_SMTP_PASSWORD: "<smtp-password>"
